// frontend/src/components/ChartList.vue
<template>
  <div class="w-100 row">
    <div class="col-3 d-none d-md-block">
      <ul id="main-navigation" class="nav flex-column">
        <li v-for="(chart, index) in charts" class="nav-item" :key="chart.id">
          <a
            class="nav-link"
            :class="{ active: index === 0 }"
            :href="`#${chart.id}`"
          >
            {{ chart.title }}
          </a>
        </li>
      </ul>
    </div>
    <div class="col-md-9 col-12">
      <template v-for="chart in charts">
        <component
          :is="chart.component"
          :id="chart.id"
          :key="chart.id + '_chart'"
        />
      </template>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import InfectedLogChart from "@/components/InfectedLogChart.vue";
import OutcomeChart from "@/components/OutcomeChart.vue";
import TestedChart from "@/components/TestedChart.vue";
import InfectedByLocationTable from "@/components/InfectedByLocationTable.vue";
import TestsPerDayChart from "@/components/TestsPerDayChart.vue";
import { VueConstructor } from "vue";
import Summary from "@/components/Summary.vue";

@Component
export default class ChartList extends Vue {
  private get charts(): {
    title: string;
    component: VueConstructor<Vue>;
    id: string;
  }[] {
    return [
      {
        title: "Súhrn",
        component: Summary,
        id: "summary",
      },
      {
        title: "Počet nakazených",
        component: InfectedLogChart,
        id: "infected-count",
      },
      {
        title: "Výsledky ochorenia",
        component: OutcomeChart,
        id: "outcome-count",
      },
      {
        title: "Počet testov",
        component: TestedChart,
        id: "tested-count",
      },
      {
        title: "Výsledky testov za deň",
        component: TestsPerDayChart,
        id: "results-per-day",
      },
      {
        title: "Prehľad podľa okresov",
        component: InfectedByLocationTable,
        id: "by-location-table",
      },
    ];
  }
}
</script>

// frontend/src/components/ChartList.svelte
<script lang="ts">
  import {
    getInfectedChartRows,
    getOutcomeChartRows,
    getTestedChartRows,
  } from "../utils";
  import Summary from "./Summary.svelte";
  import LineChart from "./LineChart.svelte";
  import TestedPerDayChart from "./TestedPerDayChart.svelte";
  import InfectedByLocationTable from "./InfectedByLocationTable.svelte";

  const charts: {
    id: string;
    title: string;
  }[] = [
    {
      id: "summary",
      title: "Súhrn",
    },
    {
      id: "infected-count",
      title: "Počet nakazených",
    },
    {
      id: "outcome-count",
      title: "Výsledky ochorenia",
    },
    {
      id: "tested-count",
      title: "Počet testov",
    },
    {
      id: "infected-increase-chart",
      title: "Výsledky testov za deň",
    },
    {
      id: "by-location-table",
      title: "Prehľad podľa okresov",
    },
  ];
</script>

<div class="row">
  <div class="col com-md-3 d-none d-md-block">
    <ul class="nav flex-column" id="main-navigation">
      {#each charts as chart, index}
        <li class="nav-item">
          <a class="nav-link" class:active={index === 0} href={`#${chart.id}`}>
            {chart.title}
          </a>
        </li>
      {/each}
    </ul>
  </div>
  <div class="col col-md-9 col-sm-12">
    <Summary {...charts[0]} />
    <LineChart {...charts[1]} chartDataGetter={getInfectedChartRows} />
    <LineChart {...charts[2]} chartDataGetter={getOutcomeChartRows} />
    <LineChart {...charts[3]} chartDataGetter={getTestedChartRows} />
    <TestedPerDayChart {...charts[4]} />
    <InfectedByLocationTable />
  </div>
</div>
