// frontend/src/components/ChartLayout.vue
<template>
  <div class="chart">
    <div class="text-center pb-3">
      <h3>{{ title }}</h3>
    </div>
    <div class="text-right py-3">
      <BFormRadioGroup
        v-model="timespanValue"
        :options="options"
        buttons
        size="sm"
        button-variant="outline-primary"
      />
    </div>
    <slot></slot>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from "vue-property-decorator";
import { BFormRadioGroup } from "bootstrap-vue";

@Component({
  components: {
    BFormRadioGroup
  }
})
export default class ChartLayout extends Vue {
  @Prop({ type: String, required: true })
  private title!: string;
  @Prop({ type: Number, required: true })
  private timespan!: number;

  private get timespanValue() {
    return this.timespan;
  }

  private set timespanValue(value) {
    this.$emit("update:timespan", value);
  }

  private options = [
    { text: "Všetko", value: -1 },
    { text: "Mesiac", value: 30 },
    { text: "Dva týždne", value: 14 }
  ];
}
</script>

<style lang="scss">
.chart {
  margin-bottom: 4em;
  min-height: 250px;
}
</style>

// frontend/src/components/ChartLayout.svelte
<script lang="ts">
  export let id: string;
  export let title: string;
  export let timespan: number;

  const options = [
    { text: "Všetko", value: -1 },
    { text: "Mesiac", value: 30 },
    { text: "Dva týždne", value: 14 },
  ];
</script>

<style lang="scss">
  .chart {
    margin-bottom: 4em;
    min-height: 250px;
  }

  .btn-group-toggle:focus {
    outline: none;
  }
</style>

<div class="chart" {id}>
  <div class="text-center pb-3">
    <h3>{title}</h3>
  </div>
  <div class="text-right py-3">
    <div
      role="radiogroup"
      tabindex="-1"
      class="btn-group-toggle btn-group btn-group-sm bv-no-focus-ring"
      id={`timespan_options_${id}`}>
      {#each options as option, index}
        <label
          class={`btn btn-sm ${option.value === timespan ? 'btn-primary' : 'btn-outline-primary'}`}
          on:click={() => {
            timespan = option.value;
          }}>
          <input
            type="radio"
            autocomplete="off"
            value={option.value}
            id={`timespan_options_${index}_${id}`}
            name={`timespan_options_${index}_${id}`} />
          <span>{option.text}</span>
        </label>
      {/each}
    </div>
  </div>
  <slot />
</div>
