// frontend/src/components/InfectedByLocationTable.svelte
<script lang="ts">
  import _ from "lodash";
  import { format } from "date-fns";
  import { Form, FormGroup, Input, Label, Spinner, Table } from "sveltestrap";
  import {
    faSortUp,
    faSortDown,
    faSort,
  } from "@fortawesome/free-solid-svg-icons";
  import type { IconDefinition } from "@fortawesome/fontawesome-common-types";
  import Icon from "fa-svelte";
  import { lastLogByLocation } from "../store";
  import {
    getCurrentSort,
    normalizeString,
    getInfectedByLocationTableRows,
  } from "../utils";
  import Pagination from "./Pagination.svelte";

  import type { TableColumn, LastLogByLocation } from "../types";

  let loading = false;
  let filter = "";
  let debouncedFilter = "";

  let limit = 10;
  let offset = 0;

  let rows: LastLogByLocation[] = [];
  let paginatedRows: LastLogByLocation[] = [];

  const columns: Record<string, TableColumn> = {
    location: {
      title: "Obec",
      sort: null,
    },
    infected: {
      title: "Nakazení",
      sort: "desc",
    },
    infected_delta: {
      title: "Rozdiel nakazených",
      sort: null,
    },
    last_updated: {
      title: "Posledný prípad",
      sort: null,
    },
  };

  function getSortIcon(columnKey: string): IconDefinition {
    switch (columns[columnKey].sort) {
      case "asc":
        return faSortUp;
      case "desc":
        return faSortDown;
      default:
        return faSort;
    }
  }

  function getSortIconClass(columnKey: string): string {
    if (columns[columnKey].sort === null) {
      return "text-muted";
    }
    return "";
  }

  function setSort(sortKey: string) {
    switch (columns[sortKey].sort) {
      case "desc":
        columns[sortKey].sort = "asc";
        break;
      case "asc":
        columns[sortKey].sort = "desc";
        break;
      default:
        for (const columnKey in columns) {
          columns[columnKey].sort = columnKey === sortKey ? "desc" : null;
        }
    }
  }

  function setFilter(value: string) {
    filter = value;
    _.debounce(() => {
      debouncedFilter = filter;
    }, 400)();
    offset = 0;
  }

  $: if ($lastLogByLocation.length) {
    rows = getInfectedByLocationTableRows(
      $lastLogByLocation,
      columns,
      debouncedFilter
    );

    paginatedRows = [...rows].splice(offset, limit);
  }
</script>

<div class="chart">
  <div class="text-center pb-3">
    <h3>Prehľad podľa okresov</h3>
  </div>
  <div id="by-location-table">
    <Form>
      <FormGroup class="row">
        <Label for="infectedByLocationFilter" class="sr-only">Hľadať</Label>
        <Input
          id="infectedByLocationFilter"
          class="col-md-4 col-sm-12"
          placeholder="Hľadať"
          readonly={false}
          on:input={(e) => setFilter(e.target.value)} />
        {#if loading}
          <div class="col-form-label pl-3 d-sm-none d-md-inline-block">
            <Spinner size="sm" color="primary" />
            <span class="sr-only">Hľadám...</span>
          </div>
        {/if}
      </FormGroup>
    </Form>
  </div>
  <Table>
    <thead role="rowgroup">
      <tr>
        {#each Object.keys(columns) as key}
          <th>
            <div
              class="cursor-pointer d-flex justify-content-between"
              on:click={() => setSort(key)}>
              <div>{columns[key].title}</div>
              <div class={getSortIconClass(key)}>
                <Icon icon={getSortIcon(key)} />
              </div>
            </div>
          </th>
        {/each}
      </tr>
    </thead>
    <tbody role="rowgroup">
      {#each paginatedRows as row}
        <tr>
          {#each Object.keys(columns) as key}
            <td>
              <span>{row[key]}</span>
            </td>
          {/each}
        </tr>
      {/each}
    </tbody>
  </Table>
  <Pagination {limit} bind:offset length={rows.length} />
</div>

// frontend/src/components/InfectedByLocationTable.vue
<template>
  <div class="chart">
    <div class="text-center pb-3">
      <h3>Prehľad podľa okresov</h3>
    </div>
    <div>
      <BForm>
        <div class="form-group row">
          <BFormInput
            class="col-md-4 col-sm-12"
            :value="filter"
            placeholder="Hľadať"
            @input="setFilter"
          />
          <template v-if="loading">
            <div class="col-form-label pl-3 d-sm-none d-md-inline-block">
              <BSpinner small variant="primary" />
              <span class="sr-only">Hľadám...</span>
            </div>
          </template>
        </div>
      </BForm>
    </div>
    <BTable
      :fields="fields"
      :items="items"
      :sort-by.sync="sortBy"
      :sort-desc.sync="sortDesc"
      :per-page="perPage"
      :current-page="page"
    />
    <BPagination
      v-model="page"
      :per-page="perPage"
      :total-rows="items.length"
      align="right"
    />
  </div>
</template>

<script lang="ts">
import { Vue, Component } from "vue-property-decorator";
import { fetchLastLogByLocation } from "@/api";
import { LastLogByLocation } from "@/types";
import {
  BTable,
  BPagination,
  BvTableFieldArray,
  BFormInput,
  BForm,
  BFormText,
  BSpinner,
} from "bootstrap-vue";
import ChartLayout from "@/components/ChartLayout.vue";
import { format } from "date-fns";
import { normalizeString } from "@/utils";
import _ from "lodash";

@Component({
  components: {
    ChartLayout,
    BTable,
    BPagination,
    BFormInput,
    BForm,
    BFormText,
    BSpinner,
  },
})
export default class InfectedByLocationTable extends Vue {
  private data: LastLogByLocation[] = [];
  private sortBy = "infected";
  private sortDesc = true;

  private perPage = 10;
  private page = 1;
  private filter = "";
  private debouncedFilter = "";

  private orderBy: { column: string; direction: "asc" | "desc" } = {
    column: "infected",
    direction: "desc",
  };
  private get fields(): BvTableFieldArray {
    return [
      {
        key: "location",
        label: "Obec",
        sortable: true,
      },
      {
        key: "infected",
        label: "Nakazení",
        sortable: true,
      },
      {
        key: "infected_delta",
        label: "Rozdiel nakazených",
        sortable: true,
      },
      {
        key: "last_updated",
        label: "Posledný prípad",
        sortable: true,
        formatter: (value) => {
          const date = new Date(value);
          return format(date, "d.M.yyyy");
        },
        sortByFormatted: (value) => new Date(value),
      },
    ];
  }

  private get items() {
    return this.data.filter((item) => {
      const filterValue = normalizeString(this.debouncedFilter);
      return normalizeString(item.location).startsWith(filterValue);
    });
  }

  private get loading() {
    return this.filter !== this.debouncedFilter;
  }

  async mounted() {
    const fetchResult = await fetchLastLogByLocation();
    this.data = fetchResult?.data?.results || [];
  }

  private setFilter(filterValue: string) {
    this.filter = filterValue;
    _.debounce(() => {
      this.debouncedFilter = filterValue;
    }, 400)();
  }
}
</script>

<style scoped></style>
