// frontend/src/components/Summary.svelte
<script lang="ts">
  import { format } from "date-fns";
  import c3 from "c3";

  import {
    formatNumber,
    getSummaryValue,
    getActiveSummaryValue,
    getChartConfig,
    getTooltipWithDeltaFormatter,
  } from "../utils";
  import { infectedLog } from "../store";
  import { InfectedLogDataKey } from "../types";

  import type { SummaryValue, InfectedLog } from "../types";
  import type { ChartConfiguration, PrimitiveArray } from "c3";

  export let id: string = "";
  export const title: string = "";

  let medianCard: SummaryValue = {
    title: "Aktuálny kĺzavý medián",
    value: "",
    delta: "",
  };
  let simpleCards: SummaryValue[] = [];
  let hospitalizedCard: { main: SummaryValue; subValues: SummaryValue[] } = {
    main: { title: "Hospitalizovaných", value: "", delta: "" },
    subValues: [],
  };

  function getChartDataRows(): PrimitiveArray[] {
    return $infectedLog.slice(-7).map((item) => {
      const date = new Date(item.date);
      const dateString: string = format(date, "yyyy-MM-dd");
      return [dateString, item[InfectedLogDataKey.MEDIAN]];
    });
  }

  function getMedianChartConfig(): ChartConfiguration {
    const rows = [["Dátum", "Medián"], ...getChartDataRows()];
    return getChartConfig({
      bindto: "#medianGraph",
      data: {
        rows,
        labels: { format: formatNumber },
      },
      tooltip: {
        format: {
          value: getTooltipWithDeltaFormatter(rows),
        },
      },
      legend: {
        show: false,
      },
      size: {
        height: 200,
      },
    });
  }

  $: lastLogs = $infectedLog.slice().reverse();

  $: if (lastLogs.length) {
    simpleCards = [
      getSummaryValue(lastLogs, InfectedLogDataKey.INFECTED, "Nakazených"),
      getSummaryValue(lastLogs, InfectedLogDataKey.TESTS, "Testovaných"),
      getSummaryValue(lastLogs, InfectedLogDataKey.DEATHS, "Úmrtia"),
      getSummaryValue(lastLogs, InfectedLogDataKey.CURED, "Vyliečení"),
      getActiveSummaryValue(lastLogs),
    ];
    hospitalizedCard = {
      main: getSummaryValue(
        lastLogs,
        InfectedLogDataKey.HOSPITALIZED,
        "Hospitalizovaných"
      ),
      subValues: [
        getSummaryValue(
          lastLogs,
          InfectedLogDataKey.CONFIRMED_HOSPITALIZED,
          "Potvrdený covid19:"
        ),
        getSummaryValue(
          lastLogs,
          InfectedLogDataKey.CONFIRMED_HOSPITALIZED_ICU,
          "Na JIS:"
        ),
        getSummaryValue(
          lastLogs,
          InfectedLogDataKey.CONFIRMED_HOSPITALIZED_VENTILATION,
          "Na ventilácií:"
        ),
      ],
    };
    medianCard = getSummaryValue(
      lastLogs,
      InfectedLogDataKey.MEDIAN,
      "Aktuálny kĺzavý medián"
    );

    c3.generate(getMedianChartConfig());
  }
</script>

<style lang="scss">
  .summary {
    margin-bottom: 4em;
    min-height: 250px;
  }
</style>

<div {id} class="summary">
  <div class="row align-content-stretch">
    <div class="col col-md-4 col-sm-12 mb-3">
      <div class="card h-100 text-center">
        <div class="card-header">
          <div class="card-title m-0">{medianCard.title}</div>
        </div>
        <div class="card-body">
          <div class="d-flex align-items-center justify-content-center h-100">
            <div>
              <h1 class="median d-inline">{medianCard.value}</h1>
              <small class="text-muted">{medianCard.delta}</small>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col col-md-8 col-sm-12 mb-3">
      <div class="card h-100 text-center">
        <div class="card-header">
          <div class="card-title m-0">Vývoj kĺzavého mediánu</div>
        </div>
        <div class="card-body">
          <div id="medianGraph" />
        </div>
      </div>
    </div>
  </div>
  <div class="row align-content-stretch">
    {#each simpleCards as card}
      <div class="col col-md-4 col-sm-12 mb-3">
        <div class="card h-100 text-center">
          <div class="card-header">
            <div class="card-title m-0">{card.title}</div>
          </div>
          <div class="card-body">
            <div
              class="py-4 d-flex align-items-center justify-content-center h-100">
              <div>
                <h3 class="d-inline">{card.value}</h3>
                <small class="text-muted">{card.delta}</small>
              </div>
            </div>
          </div>
        </div>
      </div>
    {/each}
    <div class="col col-md-4 col-sm-12 mb-3">
      <div class="card h-100 text-center">
        <div class="card-header">
          <div class="card-title m-0">{hospitalizedCard.main.title}</div>
        </div>
        <div class="card-body">
          <div
            class="d-flex flex-column align-items-center justify-content-center
            h-100">
            <div class="pb-2">
              <h4 class="d-inline">{hospitalizedCard.main.value}</h4>
              <small class="text-muted">{hospitalizedCard.main.delta}</small>
            </div>
            <table class="text-left">
              {#each hospitalizedCard.subValues as value}
                <tr>
                  <td class="pr-1">{value.title}</td>
                  <td>
                    {value.value}
                    <small class="text-muted">{value.delta}</small>
                  </td>
                </tr>
              {/each}
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// frontend/src/components/Summary.vue
<template>
  <div class="summary">
    <BRow class="align-content-stretch">
      <BCol md="4" sm="12" class="mb-3">
        <BCard header="Aktuálny kĺzavý medián" align="center" class="h-100">
          <div
            v-if="this.infectedLog.length"
            class="d-flex align-items-center justify-content-center h-100"
          >
            <div>
              <h3 class="d-inline">{{ lastLogs[0].median }}</h3>
              <small class="text-muted">
                {{
                  formatDelta(lastLogs[0].median - lastLogs[1].median)
                }}</small
              >
            </div>
          </div>
        </BCard>
      </BCol>
      <BCol md="8" sm="12" class="mb-3">
        <BCard header="Vývoj kĺzavého mediánu" align="center">
          <div id="medianGraph"></div>
        </BCard>
      </BCol>
    </BRow>
    <BRow class="align-content-stretch">
      <BCol v-for="(card, id) in cards" :key="id" md="4" sm="12" class="mb-3">
        <BCard :header="card.title" align="center" class="h-100">
          <div
            class="py-4 d-flex align-items-center justify-content-center h-100"
          >
            <div>
              <h3 class="d-inline">{{ card.value }}</h3>
              <small class="text-muted"> {{ card.delta }}</small>
            </div>
          </div>
        </BCard>
      </BCol>
    </BRow>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { fetchInfectedLog } from "@/api";
import { InfectedLog, InfectedLogDataKey } from "@/types";
import { BCard, BCol, BRow } from "bootstrap-vue";
import {
  formatNumber,
  getChartConfig,
  getTooltipWithDeltaFormatter,
} from "@/utils";
import c3, { ChartConfiguration, PrimitiveArray } from "c3";
import { format, subDays } from "date-fns";

@Component({ components: { BRow, BCol, BCard } })
export default class Summary extends Vue {
  private infectedLog: InfectedLog[] = [];

  private get lastLogs() {
    if (!this.infectedLog.length) {
      return [];
    }
    return this.infectedLog.slice().reverse();
  }

  private get cards() {
    if (!this.lastLogs.length) {
      return [];
    }
    const lastLogs = this.lastLogs;
    return [
      {
        title: "Nakazených",
        value: formatNumber(lastLogs[0].infected),
        delta: this.formatDelta(lastLogs[0].infected - lastLogs[1].infected),
      },
      {
        title: "Testovaných",
        value: formatNumber(lastLogs[0].tests),
        delta: this.formatDelta(lastLogs[0].tests - lastLogs[1].tests),
      },
      {
        title: "Úmrtia",
        value: formatNumber(lastLogs[0].deaths),
        delta: this.formatDelta(lastLogs[0].deaths - lastLogs[1].deaths),
      },
      {
        title: "Vyliečení",
        value: formatNumber(lastLogs[0].cured),
        delta: this.formatDelta(lastLogs[0].cured - lastLogs[1].cured),
      },
      {
        title: "Aktívnych",
        value: formatNumber(this.getActive(0)),
        delta: this.formatDelta(this.getActive(0) - this.getActive(1)),
      },
      {
        title: "Hospitalizovaných",
        value: formatNumber(lastLogs[0].hospitalized),
        delta: this.formatDelta(
          lastLogs[0].hospitalized - lastLogs[1].hospitalized
        ),
      },
      {
        title: "Potvrdených Hospitalizovaných",
        value: formatNumber(lastLogs[0].confirmed_hospitalized),
        delta: this.formatDelta(
          lastLogs[0].confirmed_hospitalized -
            lastLogs[1].confirmed_hospitalized
        ),
      },
      {
        title: "Na JIS",
        value: formatNumber(lastLogs[0].confirmed_hospitalized_icu),
        delta: this.formatDelta(
          lastLogs[0].confirmed_hospitalized_icu -
            lastLogs[1].confirmed_hospitalized_icu
        ),
      },
      {
        title: "Na pľúcnej ventilácií",
        value: formatNumber(lastLogs[0].confirmed_hospitalized_ventilation),
        delta: this.formatDelta(
          lastLogs[0].confirmed_hospitalized_ventilation -
            lastLogs[1].confirmed_hospitalized_ventilation
        ),
      },
    ];
  }

  private formatDelta(value: number): string {
    if (value == 0) {
      return "";
    }
    const formattedValue = formatNumber(value);
    return value > 0 ? `(+${formattedValue})` : `(${formattedValue})`;
  }

  async mounted() {
    const fetchResult = await fetchInfectedLog();
    this.infectedLog = fetchResult?.data?.results || [];
    c3.generate(this.chartConfig);
  }

  private getActive(id: number) {
    if (!this.lastLogs.length) {
      return 0;
    }
    const log = this.lastLogs[id];
    if (log) {
      return log.infected - log.deaths - log.cured;
    }
    return 0;
  }

  private get chartConfig(): ChartConfiguration {
    const rows = [["Dátum", "Medián"], ...this.chartDataRows];
    return getChartConfig(
      {
        bindto: "#medianGraph",
        data: {
          rows,
        },
        tooltip: {
          format: {
            value: getTooltipWithDeltaFormatter(rows),
          },
        },
        legend: {
          show: false,
        },
        size: {
          height: 200,
        },
      },
      7
    );
  }

  private get chartDataRows(): PrimitiveArray[] {
    return this.infectedLog
      .filter((item) => {
        const date = new Date(item.date);
        const from = subDays(new Date(), 7);
        return date > from;
      })
      .map((item) => {
        const date = new Date(item.date);
        const dateString: string = format(date, "yyyy-MM-dd");
        return [dateString, item[InfectedLogDataKey.MEDIAN]];
      });
  }
}
</script>

<style lang="scss">
.summary {
  margin-bottom: 4em;
  min-height: 250px;
}

#medianGraph {
  max-height: 200px;
}
</style>
