// frontend/src/App.vue
<template>
  <div id="app">
    <BNavbar toggleable="lg" class="navbar-dark bg-primary">
      <div class="container">
        <BNavbarBrand href="#">Koronavírus na slovensku</BNavbarBrand>
        <BNavbarNav class="ml-auto">
          <BNavItem
            href="https://github.com/ChuckBorris33/koronaslovakia"
            alt="Source"
          >
            <i class="fab fa-github"></i>
          </BNavItem>
        </BNavbarNav>
      </div>
    </BNavbar>
    <div class="container main">
      <ChartList />
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import ChartList from "@/components/ChartList.vue";
import { BNavbar, BNavbarBrand, BNavbarNav, BNavItem } from "bootstrap-vue";

@Component({
  components: {
    ChartList,
    BNavbar,
    BNavbarBrand,
    BNavbarNav,
    BNavItem
  }
})
export default class App extends Vue {}
</script>

<style lang="scss">
@import "~c3/c3.css";

$primary: #2d7dd2;
$body-color: #303036;

@import "~bootstrap/scss/bootstrap";
@import "~bootstrap-vue/dist/bootstrap-vue.css";

@import "~@fortawesome/fontawesome-free/css/all.css";

.main {
  padding-top: 4em;
}

#main-navigation {
  position: fixed;

  .active {
    font-weight: bold;
  }
}
</style>

// frontend/src/App.svelte
<svelte:head>
	<title>Korona</title>
	<link rel='icon' type='image/x-icon' href='/favicon.ico'>
</svelte:head>

<script lang="ts">
	import { Container, Navbar, NavbarBrand, Nav, NavItem, NavLink } from 'sveltestrap'
	import Icon from 'fa-svelte'
	import { faGithub } from '@fortawesome/free-brands-svg-icons'
	import ChartList from './components/ChartList.svelte'
</script>

<Navbar toggleable="lg" class="navbar-dark bg-primary">
	<Container>
		<NavbarBrand href="#">Koronavírus na slovensku</NavbarBrand>
		<Nav class="ml-auto" navbar>
			<NavItem>
				<NavLink href="https://github.com/ChuckBorris33/koronaslovakia">
					<Icon icon="{ faGithub }"></Icon>
				</NavLink>
			</NavItem>
		</Nav>
	</Container>
</Navbar>
<Container class="main">
	<ChartList/>
</Container>
